config/routes.rb
Cert::Application.routes.draw do
  devise_for :users,
      :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}

  as :user do
    get 'login', :to => 'devise/sessions#new', :as => 'new_user_session'
    get 'logout', :to => 'devise/sessions#destroy', :as => 'destroy_user_session'
    get 'signup', :to => 'devise/registrations#new', :as => 'new_user_registration'
  end

  resources :users, :except => [:show] do
    resources :certifications, :except => [:show]
  end

  resources :certifications, :except => [:show] do
    resources :certification_marks, :except => [:show], :as =>'marks', :path => 'marks'
    resource :certification_reports, :only => [:show], :as =>'reports', :path => 'reports'
    resource :certification_results, :only => [:edit, :update], :as =>'results', :path => 'results'
  end

  resources :positions, :except => [:show]

  resources :skill_types, :except => [:show] do
    resources :skills, :except => [:show]
  end

  root :to => 'dashboard#index'
end

app/models/position.rb
class Position < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  has_many :position_skills
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_filter :authenticate_user!
  authorize_resource
  
  inherit_resources
  actions :all, :except => [:show]
end

app/views/positions/_form.html.erb
<%= semantic_form_for(resource) do |form| %>
  <%= form.inputs do %>
    <%= form.input :name %>
  <% end %>

  <%= form.buttons %> or <%= link_to 'cancel', resource_class %>
<% end %>

app/views/positions/edit.html.erb
<% title 'Editing position' %>

<%= render 'form' %>

app/views/positions/index.html.erb
<% title 'Listing positions' %>

<%= table_for(@positions) %>

<br/>

<% if can?(:create, Position) %>
    <p>
      <%= link_to 'New Position', new_position_path, :class => 'button' %>
    </p>
<% end %>

app/views/positions/new.html.erb
<% title 'Create new position' %>

<%= render 'form' %>