config/routes.rb
Cert::Application.routes.draw do
  devise_for :users,
      :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}

  as :user do
    get 'login', :to => 'devise/sessions#new', :as => 'new_user_session'
    get 'logout', :to => 'devise/sessions#destroy', :as => 'destroy_user_session'
    get 'signup', :to => 'devise/registrations#new', :as => 'new_user_registration'
  end

  resources :users, :except => [:show] do
    resources :certifications, :except => [:show]
  end

  resources :certifications, :except => [:show] do
    resources :certification_marks, :except => [:show], :as =>'marks', :path => 'marks'
    resource :certification_reports, :only => [:show], :as =>'reports', :path => 'reports'
    resource :certification_results, :only => [:edit, :update], :as =>'results', :path => 'results'
  end

  resources :positions, :except => [:show]

  resources :skill_types, :except => [:show] do
    resources :skills, :except => [:show]
  end

  root :to => 'dashboard#index'
end

app/models/certification.rb
class Certification < ActiveRecord::Base
  validates :user, :position, :presence => true
  validates :result, :presence => { :if => :result_required? }

  belongs_to :user
  belongs_to :position

  has_and_belongs_to_many :experts,
                          :class_name => 'User',
                          :join_table => 'certifications_experts'

  has_many :certification_marks,
           :dependent => :destroy

  default_scope order('created_at DESC')

  def to_s
    "#{user.full_name}@#{position.name}"
  end

  def all_experts
    @all_experts ||= experts.to_a << user
  end

  def finished?
    finished_at.present?
  end

  private

  def result_required?
    finished_at.present?
  end
end

app/controllers/certifications_controller.rb
class CertificationsController < ApplicationController
  before_filter :authenticate_user!
  authorize_resource

  inherit_resources
  belongs_to :user, :optional => true
  actions :all, :except => [:show]

  private

  def collection
    @certifications ||= end_of_association_chain.accessible_by(current_ability).includes(:position, :user).uniq
  end
end

app/views/certifications/_form.html.erb
<%= semantic_form_for(resource) do |form| %>
  <%= form.inputs do %>
    <%= form.input :position %>
    <%= form.input :user %>
    <%= form.input :experts, :as => :check_boxes, :collection => User.experts %>
  <% end %>

  <%= form.buttons %> or <%= link_to 'cancel', resource_class %>
<% end %>

app/views/certifications/edit.html.erb
<% title 'Editing certification' %>

<%= render 'form' %>

app/views/certifications/index.html.erb
<% title 'Listing certifications' %>

<% content_for :head do %>
  <script type="text/javascript">
    $(function() {
      $('.certification span.finished').tipsy({fade: true, gravity: 's'});
    });
  </script>
<% end %>

<%= table_for(@certifications) do |t| %>
  <%= t.data :actions => [:edit, :destroy] do %>
    <% t.cell(:user) %>
    
    <%= t.cell(:position) do |certification| %>
      <% certification_position_with_tooltip(certification) %>
    <% end %>

    <%= t.cell(:created_at) do |certification| %>
      <% certification.created_at.to_s(:short) %>
    <% end %>

    <%= t.cell(:mark, :heading => '', :cell_html => {:class => 'actions mark_link'}) do |certification| %>
      <% link_to('Mark', [certification, :marks]) if can?(:manage, certification.certification_marks.build) %>
    <% end %>

    <%= t.cell(:report, :heading => '', :cell_html => {:class => 'actions show_link'}) do |certification| %>
      <% link_to('Report', [certification, :reports]) if can?(:read, certification) %>
    <% end %>

  <% end %>

<% end %>

<br/>

<% if can?(:create, Certification) %>
  <p>
    <%= link_to 'New certification', new_certification_path, :class => 'button' %>
  </p>
<% end %>

app/views/certifications/new.html.erb
<% title 'Create new certification' %>

<%= render 'form' %>